### ISSUE TITLE
Won't paste in terminal while vim is suspended

### ISSUE THREAD

**Issue by graue** [jasonccox/vim-wayland-clipboard#7]
Thank you for writing this!

It works for me on Ubuntu 22, except I'm running into a weird issue where I can't paste the selection while Vim is suspended:

1. Copy a line in vim using `.+y$`
2. Ctrl-Z to suspend vim and go to terminal
3. Paste via Ctrl-Shift-V

Instead of pasting the line into the terminal, nothing happens. Then when I unsuspend vim with `fg`, I see that it's pasted another copy of the line into vim, instead! Do you have any idea why this might be happening?

**Comment by jasonccox** [comment]
From what I can tell, this behavior is a side-effect of the way that wl-copy works. By default it forks and runs in the background, serving the copied data for any other process that tries to paste. If the wl-copy process is killed, the data is lost. It seems that when wl-copy is suspended (e.g. with Ctrl-Z), it prevents the copied data from being accessed until wl-copy resumes. Try this out:

1. Run `wl-copy -f sometext`. This will run in the foreground without forking due to the `-f` flag.
2. In another terminal, use Ctrl-Shift-V to paste. You should see `sometext`.
3. Use Ctrl-Z to suspend the `wl-copy ...` command from step 1.
4. In another terminal, use Ctrl-Shift-V to paste. Nothing should be pasted.
5. Use `fg` to resume the `wl-copy ...` command from step 1. `sometext` should be printed where you tried to paste it in step 4.

Anyway, long story short, when you suspend Vim it is also suspending the wl-copy command that was run when you yanked the text. Currently, the plugin runs wl-copy with `system()`, but using `job_start()` instead seems to prevent wl-copy from suspending when Vim is suspended.

Can you try out this patch to replace `system()` with `job_start()` and let me know if it fixes your issue?

```
diff --git a/plugin/wayland_clipboard.vim b/plugin/wayland_clipboard.vim
index 1f71072..f48b5d8 100644
--- a/plugin/wayland_clipboard.vim
+++ b/plugin/wayland_clipboard.vim
@@ -41,7 +41,10 @@ endif
 " pass register contents to wl-copy if the '+' (or 'w') register was used
 function! s:WaylandYank()
     if v:event['regname'] == '+' || (v:event['regname'] == 'w' && s:plus_to_w)
-        silent call system('wl-copy', getreg(v:event['regname']))
+        silent call job_start(['wl-copy', getreg(v:event['regname'])], {
+            \   "in_io": "null", "out_io": "null", "err_io": "null",
+            \   "stoponexit": "",
+            \ })
     endif
 endfunction

```

**Comment by graue** [comment]
This fixes it! Thank you so much for the quick reply. (I got distracted by other things and didn't test your fix immediately, but I really appreciate it.)
